# Generated by Django 3.1.1 on 2020-09-25 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selia_annotator', '0003_auto_20200925_1618'),
        ('selia_visualizers', '0002_auto_20200925_1646')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='userannotation',
                    name='visualizer',
                    field=models.ForeignKey(db_column='visualizers_id', help_text='Visualizer used when annotating', on_delete=django.db.models.deletion.PROTECT, to='selia_visualizers.visualizer', verbose_name='visualizer'),
                ),
            ],
            database_operations=[]
        )
    ]
